export default {
    FETCH_PROFILE: 'FETCH_PROFILE',
    FETCH_STORAGE_FILES: 'FETCH_STORAGE_FILES',
    TOGGLE_PAGE_VIEW: 'TOGGLE_PAGE_VIEW',
    TOGGLE_SIDEBAR_VIEW: 'TOGGLE_SIDEBAR_VIEW',
    // SET_USER_ID: 'SET_USER_ID',
    GET_PROFILE: 'GET_PROFILE',
    INVITE: 'INVITE',
    LOGOUT: 'LOGOUT',
    FETCH_USER_AUDIOS: 'FETCH_USER_AUDIOS',
    // UPDATE_USER_IMAGE : 'UPDATE_USER_IMAGE',
    UPDATE_USER_STATUS : 'UPDATE_USER_STATUS',
    FETCH_PUBLIC_PROFILE:'FETCH_PUBLIC_PROFILE',
    FETCH_USER_PROJECTS:'FETCH_USER_PROJECTS'
};
